services:
  - type: web
    name: finance-tracker
    env: python
    preDeployCommand: |
      echo "Render YAML is working"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn finance_tracker.wsgi:application
